/**
 * The `BriefView` argon is tested against, produced by the real renderer.
 *
 * The committed file is REGENERATED by this suite rather than typed: run it
 * with `HELIUM_WRITE_FIXTURE=1` and it rewrites
 * `contracts/brief-view-v2.fixture.json` from `buildView` over the same real
 * 2026-09-02 run every other renderer test uses. Without that variable it
 * compares instead, so a renderer change that silently alters the shape argon
 * mirrors fails here rather than in the other repo's inbox.
 * @module dsh-plugin-tenant-option-wizard/tests/brief-view-fixture
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import type { RunReport } from "@helium/core";
import {
  BRIEF_VIEW_SCHEMA_VERSION,
  buildView,
  type BriefView,
} from "../render/index.js";
import { report, SPEC } from "./fixture-report.js";

const PATH = join(
  import.meta.dirname,
  "../contracts/brief-view-v2.fixture.json",
);

/** The same run, plus the scenarios step that states the scored forecast. The
 *  reference close is the fixture run's own prior session close, quoted in the
 *  step's text so the shape argon stores is the one a live run produces. */
function withForecast(): RunReport {
  const base = report();
  return {
    ...base,
    steps: [
      ...base.steps,
      {
        task: "scenarios",
        role: "scenario-analyst",
        mode: "model",
        text: JSON.stringify({
          sections: [
            {
              title: "Base case",
              body: "Curve stays bid into the number; risk drifts lower.",
            },
          ],
          spyForecast: {
            referenceClose: { date: "2026-09-01", value: 761.78 },
            t1Down: 0.42,
            t5Down: 0.47,
          },
        }),
      },
    ],
  } as RunReport;
}

const produced = buildView(withForecast(), SPEC);
if (process.env.HELIUM_WRITE_FIXTURE === "1")
  writeFileSync(PATH, JSON.stringify(produced, null, 1) + "\n", "utf8");

const fixture = JSON.parse(readFileSync(PATH, "utf8")) as BriefView;

describe("brief-view-v2 fixture", () => {
  it("is what this build's renderer produces today", () => {
    expect(fixture).toEqual(JSON.parse(JSON.stringify(produced)));
  });

  it("is at the version this build produces", () => {
    expect(fixture.schemaVersion).toBe(BRIEF_VIEW_SCHEMA_VERSION);
  });

  it("carries a numeric target and a thesis on the first candidate", () => {
    const candidate = fixture.candidates[0]!;
    expect(typeof candidate.target!.level).toBe("number");
    expect(["above", "below"]).toContain(candidate.target!.side);
    expect(candidate.thesis.length).toBeGreaterThan(0);
    expect(candidate.resolutionDeadline).toBe(candidate.expiry);
  });

  it("carries the scorable forecast argon renders nothing from but stores", () => {
    expect(fixture.spyForecast!.scorable).toBe(true);
    expect(fixture.spyForecast!.forecast!.t1Down).toBeGreaterThanOrEqual(0);
  });

  it("has no undefined anywhere — argon renders this verbatim", () => {
    expect(JSON.stringify(fixture)).not.toContain("undefined");
  });
});
